name: flutter_2d_slider
description: A Flutter 2D Slider package. Used to select from range of 2 dimensional values with boundary.
version: 0.0.1
homepage: https://github.com/r-mzy47/flutter_2d_slider

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"
  

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
